<?xml version="1.0" encoding="UTF-8"?>
<!--
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

  Copyright (c) 2024 Payara Foundation and/or its affiliates. All rights reserved.

  The contents of this file are subject to the terms of either the GNU
  General Public License Version 2 only ("GPL") or the Common Development
  and Distribution License("CDDL") (collectively, the "License").  You
  may not use this file except in compliance with the License.  You can
  obtain a copy of the License at
  https://github.com/payara/Payara/blob/master/LICENSE.txt
  See the License for the specific
  language governing permissions and limitations under the License.

  When distributing the software, include this License Header Notice in each
  file and include the License file at glassfish/legal/LICENSE.txt.

  GPL Classpath Exception:
  The Payara Foundation designates this particular file as subject to the "Classpath"
  exception as provided by the Payara Foundation in the GPL Version 2 section of the License
  file that accompanied this code.

  Modifications:
  If applicable, add the following below the License Header, with the fields
  enclosed by brackets [] replaced by your own identifying information:
  "Portions Copyright [year] [name of copyright owner]"

  Contributor(s):
  If you wish your version of this file to be governed by only the CDDL or
  only the GPL Version 2, indicate your decision by adding "[Contributor]
  elects to include this software in this distribution under the [CDDL or GPL
  Version 2] license."  If you don't indicate a single choice of license, a
  recipient has the option to distribute your version of this file under
  either the CDDL, the GPL Version 2 or to extend the choice of license to
  its licensees as provided above.  However, if you add GPL Version 2 code
  and therefore, elected the GPL Version 2 license, then the option applies
  only if the new code is made subject to such option by the copyright
  holder.

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fish.payara.jakarta.tests.tck</groupId>
        <artifactId>tck</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mail-tck</artifactId>
    <packaging>pom</packaging>

    <name>TCK: Mail</name>

    <properties>
        <ant.home>${project.build.directory}${file.separator}apache-ant-${ant.version}</ant.home>
        <ant.zip.url>https://archive.apache.org/dist/ant/binaries/apache-ant-${ant.version}-bin.zip</ant.zip.url>
        <ant.executable>${ant.home}${file.separator}bin${file.separator}ant</ant.executable>
        <tck.home>${project.build.directory}${file.separator}mail-tck</tck.home>
        
        <javamail.username>user01%40james.local</javamail.username>
        <javamail.password>1234</javamail.password>
        <javamail.server>localhost</javamail.server>
        <javamail.smtp.port>1025</javamail.smtp.port>
        <javamail.imap.port>1143</javamail.imap.port>
    </properties>

    <dependencies>
        <dependency>
            <groupId>fish.payara.jakarta.tests.tck</groupId>
            <artifactId>jakarta-mail-tck</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Download Ant -->
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>download-ant</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>wget</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <skip>${skipTests}</skip>
                    <url>${ant.zip.url}</url>
                    <unpack>true</unpack>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                </configuration>
            </plugin>

            <!-- Unpack Payara and TCK -->
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <configuration>
                    <skip>${skipTests}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>unpack-tck</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeArtifactIds>jakarta-mail-tck</includeArtifactIds>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Configure and run TCK -->
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.ant</groupId>
                        <artifactId>ant</artifactId>
                        <version>${ant.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>ant-contrib</groupId>
                        <artifactId>ant-contrib</artifactId>
                        <version>1.0b3</version>
                        <exclusions>
                            <exclusion>
                                <groupId>ant</groupId>
                                <artifactId>ant</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                </dependencies>
                <configuration>
                    <skip>${skipTests}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>prepare-tck-and-payara</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target xmlns:if="ant:if" xmlns:unless="ant:unless">
                                <taskdef resource="net/sf/antcontrib/antcontrib.properties" classpathref="maven.plugin.classpath" />

                                <macrodef name="tck-setting">
                                    <attribute name="key" /> <attribute name="value" />
                                    <sequential>
                                        <replaceregexp file="${tck.home}/lib/ts.jte" byline="true"
                                                       match="@{key}=.*" replace="@{key}=@{value}" />
                                        <replaceregexp file="${tck.home}/lib/ts.pluggability.jte" byline="true"
                                                       match="@{key}=.*" replace="@{key}=@{value}" />
                                    </sequential>
                                </macrodef>


                                <!-- Change configuration -->

                                <tck-setting key="TS_HOME" value="${tck.home}"/>
                                <tck-setting key="ANT_HOME" value="${ant.home}"/>
                                <tck-setting key="JAVA_HOME" value="${java.home}"/>
                                <tck-setting key="JARPATH" value="${payara.home}/glassfish/modules"/>
                                <tck-setting key="JAVAMAIL_SERVER" value="${javamail.server}"/>
                                <tck-setting key="JAVAMAIL_USERNAME" value="${javamail.username}"/>
                                <tck-setting key="JAVAMAIL_PASSWORD" value="${javamail.password}"/>
                                <tck-setting key="JAVAMAIL_ROOT_PATH" value="/"/>
                                <tck-setting key="SMTP_USERNAME" value="${javamail.username}"/>
                                <tck-setting key="SMTP_DOMAIN" value="${javamail.server}"/>
                                
                                <replace file="${tck.home}/build.xml">
                                    <replacetoken><![CDATA[<sysproperty key="testDebug" value="${tests.debug}"/>]]></replacetoken>
                                    <replacevalue><![CDATA[<sysproperty key="testDebug" value="${tests.debug}"/>
                                <jvmarg value="-Djavatest.security.noSecurityManager=true"/>]]></replacevalue>
                                </replace>
                                
                            </target>
                        </configuration>
                    </execution>


                    <execution>
                        <id>run-tck-tests</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target xmlns:if="ant:if" xmlns:unless="ant:unless">
                                <taskdef resource="net/sf/antcontrib/antcontrib.properties" classpathref="maven.plugin.classpath" />

                                <echo level="info" message="Start running all tests" />
                                <exec executable="${ant.executable}" dir="${tck.home}" resultproperty="testResult">
                                    <arg value="run" />
                                    <arg value="run.pluggability" />
                                    <arg value="-DfailOnError=false" />
                                    <env key="TS_HOME" value="${tck.home}"/>
                                    <env key="ANT_HOME" value="${ant.home}"/>
                                    <env key="JARPATH" value="${payara.home}/glassfish/modules"/>
                                    <env key="AS_JAVA" value="${java.home}"/>
                                    <env key="JAVA_HOME" value="${java.home}"/>
                                    <env key="LC_ALL" value="C" />
                                </exec>

                                <if>
                                    <not>
                                        <equals arg1="${testResult}" arg2="0" />
                                    </not>
                                    <then>
                                        <echo message="Running tests failed." />
                                        <loadfile property="contents" srcFile="${payara.home}${file.separator}glassfish${file.separator}domains${file.separator}domain1${file.separator}logs${file.separator}server.log" />
                                        <echo message="${contents}" />
                                    </then>
                                </if>

                                <if>
                                    <not>
                                        <equals arg1="${testResult}" arg2="0" />
                                    </not>
                                    <then>
                                        <fail/>
                                    </then>
                                </if>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Run Docker image james-mail -->
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.45.1</version>
                
                <configuration>
                    <images>
                        <image>
                            <name>jakartaee/cts-mailserver:0.1</name>
                            <alias>james-mail</alias>
                            <run>
                                <ports>
                                    <port>${javamail.smtp.port}:${javamail.smtp.port}</port>
                                    <port>${javamail.imap.port}:${javamail.imap.port}</port>
                                </ports>
                                <entryPoint>
                                    <shell>/bin/bash /root/startup.sh</shell>
                                </entryPoint>
                                <wait>
                                    <time>30000</time>
                                    <exec>
                                        <postStart>/bin/bash /root/create_users.sh</postStart>
                                    </exec>
                                </wait>
                            </run>
                        </image>
                    </images>
                    <executeStopOnVMShutdown>true</executeStopOnVMShutdown>
                </configuration>
                <executions>
                    <execution>
                        <id>start-docker</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-docker</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                  <execution>
                    <id>populate mail server</id>
                    <phase>generate-test-resources</phase>
                    <goals>
                        <goal>exec</goal>
                    </goals>
                  </execution>
                </executions>
                <configuration>
                    <mainClass>fpopulate</mainClass>
                    <includeProjectDependencies>false</includeProjectDependencies>
                    <includePluginDependencies>true</includePluginDependencies>
                    <executable>java</executable>
                    <arguments>
                        <argument>-classpath</argument>
                        <argument>${payara.home}/glassfish/modules/jakarta.mail-api.jar;${payara.home}/glassfish/modules/jakarta.activation-api.jar;${payara.home}/glassfish/modules/angus-mail.jar;${payara.home}/glassfish/modules/angus-activation.jar</argument>
                        <argument>fpopulate.java</argument>
                        <argument>-s</argument>
                        <argument>test1</argument>
                        <argument>-d</argument>
                        <argument>imap://${javamail.username}:${javamail.password}@${javamail.server}:${javamail.imap.port}</argument>
                    </arguments>
                    <workingDirectory>${tck.home}/tests/mailboxes</workingDirectory>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>jakarta.mail</groupId>
                        <artifactId>jakarta.mail-api</artifactId>
                        <version>2.1.3</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <ant.executable>${ant.home}${file.separator}bin${file.separator}ant.cmd</ant.executable>
            </properties>
        </profile>
    </profiles>
</project>